### ISSUE TITLE
amazon 检测出来是webdriver

### ISSUE THREAD

**Issue by SwallowData** [kimbleex/AmazonSpider#2]
用webdriver 打开amazon时要求填写账户

**Comment by kimbleex** [comment]
是的，所以可以使用google账户登录让浏览器记住你的缓存，详细可看我的个人博客https://blog.kimbleex.top/Programming/Selenium-Read-UsersInfo/

**Comment by SwallowData** [comment]
我用账号登录后会产生这样的错误
![image](https://github.com/user-attachments/assets/6c92df94-c5ba-46c4-ae74-7256ae36c017)
在正常浏览器就不会

**Comment by SwallowData** [comment]
##我的代码如下##
class AmazonSpider(object):

    def star_browser(self):
        # 获取计算机用户名
        username = os.getlogin()
        self.browser_path = 'C:/Users/{}/AppData/Local/Google/Chrome/User Data'.format(username)
        options = webdriver.ChromeOptions()        
        cookies = [
            {'name': 'session-id', 'value': '146-5230554-9272453'},
            {'name': 'another_cookie', 'value': 'another_value'},
            # 可以添加多个 Cookie，格式相同
        ]
        options.add_argument('lang=en-US')
        options.add_argument(
            "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36")
        #设置反反爬虫标识，让浏览器检测不到selenium
        options.add_experimental_option('excludeSwitches', ['enable-automation'])

        self.browser = webdriver.Chrome(options=options)

        # 窗口最大化
        self.browser.maximize_window()
    def login(self):
        self.browser.get('https://www.amazon.com/')
        input('请手动登录，登录成功后按任意键继续')
        try:
            self.browser.refresh()
            # 保存登录成功后的 Cookie 到文件
            cookies = self.browser.get_cookies()
            with open('cookies.json', 'w') as f:
                json.dump(cookies, f)
            print('成功获取文件')
        except:
            print("登录失败,刷新失败!")
        time.sleep(1000)
azs = AmazonSpider()
azs.star_browser()
azs.login()

**Comment by SwallowData** [comment]
> ##我的代码如下## class AmazonSpider(object):
> 
> ```
> def star_browser(self):
>     # 获取计算机用户名
>     username = os.getlogin()
>     self.browser_path = 'C:/Users/{}/AppData/Local/Google/Chrome/User Data'.format(username)
>     options = webdriver.ChromeOptions()        
>     cookies = [
>         {'name': 'session-id', 'value': '146-5230554-9272453'},
>         {'name': 'another_cookie', 'value': 'another_value'},
>         # 可以添加多个 Cookie，格式相同
>     ]
>     options.add_argument('lang=en-US')
>     options.add_argument(
>         "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36")
>     #设置反反爬虫标识，让浏览器检测不到selenium
>     options.add_experimental_option('excludeSwitches', ['enable-automation'])
> 
>     self.browser = webdriver.Chrome(options=options)
> 
>     # 窗口最大化
>     self.browser.maximize_window()
> def login(self):
>     self.browser.get('https://www.amazon.com/')
>     input('请手动登录，登录成功后按任意键继续')
>     try:
>         self.browser.refresh()
>         # 保存登录成功后的 Cookie 到文件
>         cookies = self.browser.get_cookies()
>         with open('cookies.json', 'w') as f:
>             json.dump(cookies, f)
>         print('成功获取文件')
>     except:
>         print("登录失败,刷新失败!")
>     time.sleep(1000)
> ```
> 
> azs = AmazonSpider() azs.star_browser() azs.login()

**Comment by SwallowData** [comment]
解决了，方法是在selenium 打开的浏览器中注册amazon账号
另外amazon账号的购买好贵，有什么什么便宜的方式可以获取amazon账号

**Comment by kimbleex** [comment]
我是谷歌账号直接登陆的，之前注册gmail中国手机还可以验证，不知道现在行不行。

**Comment by SwallowData** [comment]
> 我是谷歌账号直接登陆的，之前注册gmail中国手机还可以验证，不知道现在行不行。

现在是个别中国手机号可以申请，我联通的不行，移动的行。
